### ISSUE TITLE
Tail Errror (No such file or directory)

### ISSUE THREAD

**Issue by STX2k** [dimitrijp/Organizr-Nginx#1]
I get an error if i want to build the package

    root@xxxxxx:/usr/local/src# dpkg-buildpackage -uc -b -j4
    tail: cannot open 'debian/changelog' for reading: No such file or directory
    dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1

I checked the steps again but same error.

**Comment by dimitrijp** [comment]
You shoul be in cd /usr/local/src/nginx-1.13.5/ when running build command. I will update the wiki. Please try if its working.
