### ISSUE TITLE
403 Error - White Site

### ISSUE THREAD

**Issue by STX2k** [dimitrijp/Organizr-Nginx#2]
Hey, 
thank you for your Configs and HowTo. 

I follow your steps and setup all needed things. But i only get an 403 Error when i try to open organizer. I checked all twice. I run php7.1 

i followed these steps for php https://www.rosehosting.com/blog/install-php-7-1-with-nginx-on-an-ubuntu-16-04-vps/

I hope you can help me.

**Comment by dimitrijp** [comment]
what if you try to open www.yourdomain/check.php?, this guide assume that you have domain name available and 80 and 443 port forwards on your router. What your nginx error and access log shows?

**Comment by dimitrijp** [comment]
additional test..comment out geoIP blocking stuff if you use it, and test again.
