### ISSUE TITLE
Issue with header.conf

### ISSUE THREAD

**Issue by miamitk** [dimitrijp/Organizr-Nginx#3]
I followed the guide.

When running nginx -t there is an issue with header.conf.

nginx: [emerg] unexpected "n" in /etc/nginx/header.conf:8
nginx: configuration file /etc/nginx/nginx.conf test failed

I couldn't find any issues I copied it as you instructed.

Contents of Header.

```
####################################
#  filename /etc/nginx/header.conf                 #
####################################
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; prel$
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "same-origin" always;
add_header X-Frame-Options "SAMEORIGIN";
```

**Comment by dimitrijp** [comment]
Delete the file and create it again, check for typos.. there should be no issues inside this file.

**Comment by dimitrijp** [comment]
Btw copy contents from files on git... maybee there is formatting mistacke in wiki... i will double check it. Let me know how it goes.

**Comment by miamitk** [comment]
Yes that fixed it :)  I took it from the git.

**Comment by dimitrijp** [comment]
there was a typo in wiki..corrected now. Thanks for letting me know.
